version: '3.8'

services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: cms-apache-php
    volumes:
      - ./project:/var/www/html
    ports:
      - "8070:80"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_username
      MYSQL_PASSWORD: db_password
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
